# Generated by Django 3.2.9 on 2022-01-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner_enrolled_courses',
            old_name='student_id',
            new_name='lecture_id',
        ),
    ]
