# Generated by Django 3.2.9 on 2022-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_app', '0002_rename_student_id_learner_enrolled_courses_lecture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner_enrolled_courses',
            name='learner_id',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
