# Generated by Django 3.2.9 on 2022-01-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_app', '0004_alter_lecture_classes_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_enrolled_courses',
            name='learner_id',
            field=models.IntegerField(default=None),
        ),
    ]
