# Generated by Django 3.2.9 on 2022-01-11 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learner_app', '0007_auto_20220111_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_enrolled_courses',
            name='learner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
